### ISSUE TITLE
Queue Time not showing

### ISSUE THREAD

**Issue by Nthingxhere** [andrsdt/spicetify-show-queue-duration#1]
![grafik](https://user-images.githubusercontent.com/76117403/235440099-8e801c4f-18da-42b4-a968-0ddc13afa409.png)

The Queue Timer is not showing even after I reinstalled the extenstion I am running Spicetify Version 2.17.2 and Spotify Version  1.2.10.720

I hope this text doesn't sound rude

**Comment by jetdzhet** [comment]
Same thing's happening to me, most likely we have to wait for extension to get updated

**Comment by andrsdt** [comment]
@Nthingxhere @jetdzhet Not rude at all! Thanks for letting me know. This problem may appear sometimes when Spotify gets updated.

I have updated the extension and it's working now in my current build:

```
Spotify for Windows
1.2.10.760.g52970952
Spicetify v2.17.2
```

Please, confirm that it's working for you too. You may have to delete and reinstall the extension from the Spicetify Marketplace, though it was not necessary for me. In case it's still not working, it could be because you a using a different OS or Spotify version. Tell me and I will give you more instructions on how to debug it.
